
# html lang
language: zh

favicon: 🏕️

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /links

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Noto+Serif+SC:500,700&display=swap # for font

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  Github: https://github.com/TJKkking
  Email: 2510399607@qq.com
  Rss: xxx
# and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
archives: true
categories: true
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: xxxxxx

# commend module
comment:
  enable: false
  appId: xxx
  appKey: xxx
  placeholder: Say something...
  notify: false
  verify: false
  avatar: mp
